export {
  RECORD_SAMPLE_PAGES,
  RETRY_MIN_GROUP_ITEMS,
  askChunked,
  chooseRecordFields,
  compile,
  probeEntry,
  type CompileNoItems,
  type CompileOptions,
  type CompileResult,
  type CompileSuccess,
  type EntryMode,
  type ItemSpec,
  type RecordChoice,
  type RecordChoiceOptions,
} from "./compile.js";
export {
  CHUNK_BUDGET_CHARS,
  FIELD_QUESTION_PREFIX,
  LABEL_VALUE_CHARS,
  applyFieldAnswers,
  batchChars,
  buildFieldQuestions,
  candidateKey,
  candidateContext, candidateContexts, candidateLabel,
  chunkQuestions,
  fieldQuestionId,
  intersectCandidates,
  toAlternative,
  type CompileField,
  type FieldCandidate,
  type LeafAttr,
  type LeafSpec,
  type SampleResolver,
} from "./fields.js";
export {
  FAMILIES,
  REFUSE_FALLBACK,
  REFUSE_SOLE,
  auditSelector,
  gateAlternative,
  type FamilyPolicy,
  type GateDecision,
  type GateOptions,
  type RiskFamily,
  type SelectorAudit,
  type SelectorRisk,
} from "./gate.js";
export { GROUP_QUESTION_ID, RETRY_SUFFIX, buildGroupQuestion, groupLabel, isDegenerateGroup, itemFromGroup } from "./groups.js";
export {
  DETAIL_LINK_QUESTION_ID,
  NEXT_LINK_QUESTION_ID,
  buildDetailLinkQuestion,
  buildNextLinkQuestion,
  chosenIndex,
  detailLinkCandidates,
  linkLabel,
  nextLinkCandidates,
  paginationFrom,
} from "./links.js";
export {
  MAX_ALTERNATIVES,
  NothingCompilableError,
  compileFromReconciliation,
  renderRationale,
  type AlternativeRationale,
  type CompileRationale,
  type FieldRationale,
  type ProvenCompile,
  type ProvenCompileOptions,
  type RefusedAlternative,
  type UnboundField,
} from "./proven.js";
export {
  chooserOf,
  compileTemplate,
  describeFrom,
  domTier,
  investigateTemplate,
  type ChooserSource,
  type DomTierOptions,
  type InvestigateTemplateOptions,
  type RenderPages,
  type TemplateCompile,
  type TemplateCompileOptions,
  type TemplateSources,
} from "./template.js";
