export {
  LIST_SOURCE_EXTENSIONS,
  REQUEST_HANDLER_TIMEOUT_SECS,
  loadListSources,
  makeRequestGuard,
  runCrawl,
  type CrawlActor,
  type CrawlDeps,
  type HealContext,
  type HealFailure,
  type HealOutcome,
  type HealerHook,
  type NavigateContext,
  type NavigateOutcome,
  type NavigatorHook,
  type PaginateHook,
  type RequestLabel,
} from "./crawler.js";
export {
  entryModeFor,
  replayTrace,
  resolveLocator,
  scrollToBottom,
  type EntryMode,
  type ReplayPolicy,
  type ReplayTraceOptions,
  type ReplayTraceResult,
  type StepFailureAction,
} from "./entry.js";
export {
  DETAIL_LINK_FIELD,
  DETAIL_QUESTION_PREFIX,
  DETAIL_SAMPLE_PAGES,
  compileDetail,
  detailLinkOf,
  detailScraper,
  extractDetail,
  hasDetailTemplate,
  mergeDetail,
  prefixQuestions,
  withDetailLink,
  type CompileDetailOptions,
  type CompileDetailResult,
} from "./detail.js";
export {
  DEFAULT_REPLAYS,
  DEFAULT_SAMPLE_URLS,
  isUnstable,
  judgeDeterminism,
  measureDeterminism,
  readingOf,
  summarizeDeterminism,
  unstableFields,
  type AlternativeDisagreement,
  type Determinism,
  type DeterminismDriver,
  type DeterminismForm,
  type DeterminismOptions,
  type FieldStability,
  type ItemValues,
  type Movement,
  type PageReading,
  type Stability,
  type UrlReadings,
  type UrlRecord,
} from "./determinism.js";
export {
  HEAL_QUESTION_PREFIX,
  HEAL_STEP_QUESTION_PREFIX,
  controlLabel,
  createHealer,
  fieldHealQuestionId,
  findUnmappedCandidates,
  fitsStep,
  isFieldHealingEvent,
  isStepHealingEvent,
  isUnmappedCandidate,
  looksLikeBadge,
  stepHealQuestionId,
  unmappedFrom,
  type FieldHealingEvent,
  type HealingEvent,
  type StepHealingEvent,
  type UnmappedCandidate,
} from "./heal.js";
export {
  MAX_SCROLL_ROUNDS,
  NEXT_LINK_TIMEOUT_MS,
  SCROLL_GROWTH_TIMEOUT_MS,
  defaultPaginate,
  followNextLink,
  paginate,
  scrollForMore,
} from "./paginate.js";
